routes/web.php
<?php

// Admin Panel
Route::group([
    'prefix' => 'admin',
    'middleware' => [/*'auth',*/ 'admin'],
    'as' => 'admin.',
], function () {
    Route::get('/', 'AdminController@index')->name('index');

    Route::resource('users', 'UserController', ['except' => ['show']] );
	Route::get('users/{user}/delete', 'UserController@destroy')->name('users.delete');

    Route::resource('pages', 'PageController', ['except' => ['show']] );
	Route::get('pages/{page}/delete', 'PageController@destroy')->name('pages.delete');

	Route::resource('cuisines', 'CuisineController', ['except' => ['show']] );
    Route::get('cuisines/{cuisine}/delete', 'CuisineController@destroy')->name('cuisines.delete');

    Route::resource('categories', 'CategoryController', ['except' => ['show']] );
	Route::get('categories/{category}/delete', 'CategoryController@destroy')->name('categories.delete');

	Route::resource('dishes', 'DishController', ['except' => ['show']] );
    Route::get('dishes/{dish}/delete', 'DishController@destroy')->name('dishes.delete');

	Route::resource('cooks', 'CookController', ['except' => ['show']] );
    Route::get('cooks/{cook}/delete', 'CookController@destroy')->name('cooks.delete');

    Route::resource('orders', 'OrderController', ['only' => ['index', 'edit', 'update']] );

	Route::resource('reviews', 'ReviewController', ['except' => ['show']] );
	Route::get('reviews/{review}/delete', 'ReviewController@destroy')->name('reviews.delete');

    Route::group(['prefix' => 'menus', 'as' => 'menus.'], function () {
        Route::get('/', 'MenuController@index')->name('index');
	    Route::post('{menu}', 'MenuController@store')->name('store');
        Route::get('{menu}', 'MenuController@show')->name('show');
        Route::get('move/{link}/{direction}', 'MenuController@move')->name('move');
        Route::get('delete/{link}', 'MenuController@delete')->name('delete');
        Route::get('edit', 'MenuController@edit')->name('edit');
        Route::post('edit', 'MenuController@update')->name('update');
    });
});


Route::get('/activate/{token}', 'Api\AuthController@activate');


//Auth::routes();


// Vue routes
Route::get('/{vue_capture?}', function() {
	return view( 'vue');
})->where('vue_capture', '[\/\w\.-]*')->name('vue');

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{

	protected $fillable =
		[
			'alias',
			'title',
		];


	public function items()
	{
		return $this->hasMany(MenuItem::class);
	}
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\MenuRequest;
use App\Menu;
use App\MenuItem;
use App\Page;
use Illuminate\Http\Request;

class MenuController extends Controller
{

    /**
     * Отображение списка всех меню.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $menus = Menu::all();

        return view('admin.menus.index', compact('menus'));
    }

    /**
     * Добавление пункта меню.
     *
     * @param \App\Http\Requests\MenuRequest $request
     * @param                                $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(MenuRequest $request, $id)
    {
        // Получаем меню и колличество пунктов
        $menu  = Menu::find($id);
        $count = $menu->items()
            ->where('parent_id', $request->parent_id)
            ->count();

        // Данные пункта меню
        $data = [
            'type'          => $request->type,
            'page_id'       => $request->type === 'page'
                ? $request->page_id
                : null,
            'url'           => $request->type === 'url'
                ? $request->url
                : null,
            'url_title'     => $request->type === 'url'
                ? $request->url_title
                : null,
            'submenu_title' => $request->type === 'submenu'
                ? $request->submenu_title
                : null,
            'parent_id'     => $request->parent_id,
            'weight'        => ++$count,
        ];

        // Сохраняем пункт
        $menu->items()->create($data);

        return redirect()
            ->route('admin.menus.show', $menu->id)
            ->with("success", "Запись успешно создана!");
    }

    /**
     * Отображение пунктов выбранного меню
     *
     * @param $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show($id)
    {
        // Находим меню
        $menu = Menu::find($id)->load('items');

        // Формируем список всех страниц для формы
        $pages_select = ['-выберите страницу-'];
        foreach (Page::all() as $page) {
            $pages_select[$page->id] = $page->title;
        }

        // Формируем список всех подменю текущего меню для формы
        $parents_select = ['-нет-'];
        foreach ($menu->items->where('type', 'submenu') as $link) {
            $parents_select[$link->id] = $link->submenu_title;
        }

        return view('admin.menus.show',
            compact('menu', 'pages_select', 'parents_select'));
    }


    /**
     * Перемещение пункта меню вниз/вверх
     *
     * @param $id
     * @param $direction
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function move($id, $direction)
    {
        // Находим пункт
        $item = MenuItem::find($id);

        // Записываем новую позицию текущего пункта в переменную
        if ($direction === 'up') {
            $weight = $item->weight - 1;
        } elseif ($direction === 'down') {
            $weight = $item->weight + 1;
        }

        // Находим пункт для обмена позициями
        $item_exchange = MenuItem::where('menu_id', $item->menu_id)
            ->where('parent_id', $item->parent_id)
            ->where('weight', $weight)->first();

        // Меняем позицию пункта для обмена
        $item_exchange->update(['weight' => $item->weight]);

        // Меняем позицию текущего пункта
        $item->update(['weight' => $weight]);

        return redirect()
            ->back()
            ->with("success", "Запись успешно перемещена!");
    }


    /**
     * Удаление пункта меню
     *
     * @param $id
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function delete($id)
    {
        // Находим пункт
        $item = MenuItem::find($id);

        // Удаляем пункт и сдвигаем позиции нижележащих пунктов вверх
        if ($this->deleteMenuItems($item)) {
            $this->shiftMenuItems($item);

            return redirect()
                ->back()
                ->with("success", "Запись успешно удалена!");
        }
    }


    /**
     * Удаление пункта меню и всех его дочерних пунктов
     *
     * @param $item
     *
     * @return bool
     */
    private function deleteMenuItems($item)
    {
        // Находим дочерние пункты текущего пункта
        $children = MenuItem::where('menu_id', $item->menu_id)
            ->where('parent_id', $item->id)
            ->get();

        // Если есть дочерние пункты
        if ($children->count() > 0) {
            // Рекурсивно ищем в них дочерние пункты
            foreach ($children as $link) {
                $this->deleteMenuItems($link);

                // Удаляем дочерний пункт
                $link->delete();
            }
        }

        // Удаляем текущий пункт
        $item->delete();

        return true;
    }


    /**
     * Смещение номера пунктов меню после удаленного
     *
     * @param $item
     */
    private function shiftMenuItems($item)
    {
        // Находим пункты позиции которых ниже текущего
        $items = MenuItem::where('menu_id', $item->menu_id)
            ->where('parent_id', $item->parent_id)
            ->where('weight', '>', $item->weight)
            ->get();

        // Меняем позицию каждого пункта на единицу вверх
        foreach ($items as $link) {
            $weight = $link->weight - 1;
            $link->update(['weight' => $weight]);
        }

        return;
    }
}

resources/views/admin/menus/add_item_layout.blade.php
<div class="overlay">
    <div class="add-nav-item">
        <button class="close-btn">
            <i class="fa fa-times" aria-hidden="true"></i>
        </button>

        <div class="buttons">
            <button class="active">
                <label for="url">Ссылка</label>
            </button>
            <button>
                <label for="page">Страница</label>
            </button>
            <button>
                <label for="submenu">Подменю</label>
            </button>
        </div>

        {!! Form::open(['route'=>['admin.menus.store', $menu->id]]) !!}
        {!! Form::radio('type', 'url', true, ['id'=>'url', 'hidden']) !!}
        {!! Form::radio('type', 'page', null, ['id'=>'page', 'hidden']) !!}
        {!! Form::radio('type', 'submenu', null, ['id'=>'submenu', 'hidden']) !!}
        <div class="group url active">
            {!! Form::label('Имя пункта') !!}
            {!! Form::text('url_title', null, ['placeholder'=>'имя пункта']) !!}
        </div>
        <div class="group url active">
            {!! Form::label('Ссылка') !!}
            {!! Form::text('url', 'http://', ['placeholder'=>'ссылка (http://...)']) !!}
        </div>
        <div class="group page">
            {!! Form::label('Страница') !!}
            {!! Form::select('page_id', $pages_select, null) !!}
        </div>
        <div class="group submenu">
            {!! Form::label('Подменю') !!}
            {!! Form::text('submenu_title', null, ['placeholder'=>'имя пункта']) !!}
        </div>
        <div class="group">
            {!! Form::label('Родительский пункт') !!}
            {!! Form::select('parent_id', $parents_select, null) !!}
        </div>
        <div class="group">
            {!! Form::submit('Добавить пункт меню', ['class' => 'submit']) !!}
        </div>
        {!! Form::close() !!}
    </div>
</div>

resources/views/admin/menus/edit.blade.php
@extends('layouts.admin')

@section('pageDescription', '')
@section('pageTitle', 'Админпанель | ')

@section('breadcrumb', Breadcrumbs::render(Route::currentRouteName(), $nav))

@section('content')
    {!! Form::open(['action'=>['AdminController@navUpdate', $nav]]) !!}

    @foreach($menu as $link)
        <div class="group">
            {!! Form::selectRange("links[{$link->id}][weight]", 1, $menu->count(), $link->weight, ['class'=>'small']) !!}
            {!! Form::select("links[{$link->id}][page_id]", $pages_select, $link->page_id) !!}
            {!! Form::select("links[{$link->id}][parent_id]", $parents_select, $link->parent_id) !!}
        </div>

        <div class="group">
            @if($errors->has("links.{$link->id}.weight"))
                <p class="error">{{ $errors->first("links.{$link->id}.weight") }}</p>
            @endif

            @if($errors->has("links.{$link->id}.page_id"))
                <p class="error">{{ $errors->first("links.{$link->id}.page_id") }}</p>
            @endif

            @if($errors->has("links.{$link->id}.parent_id"))
                <p class="error">{{ $errors->first("links.{$link->id}.parent_id") }}</p>
            @endif
        </div>
    @endforeach

    <div class="group">
        {!! Form::submit('Сохранить изменения', ['class' => 'submit']) !!}
    </div>
    {!! Form::close() !!}
@endsection

resources/views/admin/menus/index.blade.php
@extends('layouts.admin')

@section('pageDescription', '')
@section('pageTitle', 'Админпанель | ')

@section('breadcrumb', Breadcrumbs::render(Route::currentRouteName()))

{{--@section('new-item')--}}
    {{--<a href="#" class="add add-item-btn">Новый пункт</a>--}}
{{--@endsection--}}

@section('content')
    <table>
        <tr>
            <th>ID</th>
            <th>alias</th>
            <th>Имя меню</th>
            <th>Кол-во элементов</th>
        </tr>
        @foreach($menus as $menu)
            <tr>
                <td class="small">
                    {{ link_to_route('admin.menus.show', $menu->id, [$menu->id]) }}
                </td>
                <td>{{ $menu->alias }}</td>
                <td>{{ $menu->title }}</td>
                <td>{{ $menu->items()->count() }}</td>
            </tr>
        @endforeach
    </table>
@endsection

resources/views/admin/menus/menu_items.blade.php
<ul class="menu-list">
    @foreach($current as $link)
        <li>
            <div class="info">
                @if($link->type == 'url')
                    <span>Ссылка: </span>{{ $link->url_title }} (<i>{{ link_to($link->url) }})</i>
                @elseif($link->type == 'page')
                    <span>Страница: </span>{{ $link->page->title }}
                @elseif($link->type == 'submenu')
                    <span>Подменю: </span>{{ $link->submenu_title }}
                @endif

                <div class="buttons">
                    <a href="">
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                    </a>
                    <a href="{{ route('admin.menus.delete', ['id' => $link->id]) }}" class="delete-item-btn">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </a>
                    <div class="move">
                        @if($link->weight > 1)
                            <a href="{{ route('admin.menus.move', ['id' => $link->id, 'direction' => 'up']) }}">
                                <i class="fa fa-arrow-up" aria-hidden="true"></i>
                            </a>
                        @else
                            <a href="" class="not-active">
                                <i class="fa fa-arrow-up" aria-hidden="true"></i>
                            </a>
                        @endif

                        @if($link->weight < $current->count())
                            <a href="{{ route('admin.menus.move', ['id' => $link->id, 'direction' => 'down']) }}">
                                <i class="fa fa-arrow-down" aria-hidden="true"></i>
                            </a>
                        @else
                            <a href="" class="not-active"><i class="fa fa-arrow-down" aria-hidden="true"></i></a>
                        @endif
                    </div>
                </div>
            </div>

            @if($link->type == 'submenu')
                {!! view('admin.menus.menu_items', [
                    'nav' => $nav,
                    'items' => $items->sortBy('weight'),
                    'current' => $items->where('parent_id', $link->id)
                                       ->sortBy('weight')
                ]) !!}
            @endif
        </li>
    @endforeach
</ul>

resources/views/admin/menus/show.blade.php
@extends('layouts.admin')

@section('pageDescription', '')
@section('pageTitle', 'Админпанель | ')

@section('breadcrumb', Breadcrumbs::render(Route::currentRouteName(), $menu))

@section('new-item')
    <a href="#" class="add add-item-btn">Новый пункт</a>
@endsection

@section('content')
    @if($errors->has('url_title'))
        <p class="error">{{ $errors->first('url_title') }}</p>
    @endif
    @if($errors->has('url'))
        <p class="error">{{ $errors->first('url') }}</p>
    @endif
    @if($errors->has('page_id'))
        <p class="error">{{ $errors->first('page_id') }}</p>
    @endif
    @if($errors->has('submenu_title'))
        <p class="error">{{ $errors->first('submenu_title') }}</p>
    @endif
    @if($errors->has('parent_id'))
        <p class="error">{{ $errors->first('parent_id') }}</p>
    @endif

    {!! view('admin.menus.menu_items', [
        'nav' => $menu->alias,
        'items' => $menu->items->sortBy('weight'),
        'current' => $menu->items->where('parent_id', 0)->sortBy('weight')
    ]) !!}

    {!! view('admin.menus.add_item_layout',
        compact('menu', 'pages_select', 'parents_select')
    ) !!}


@endsection