routes/web.php
<?php

// Admin Panel
Route::group([
    'prefix' => 'admin',
    'middleware' => [/*'auth',*/ 'admin'],
    'as' => 'admin.',
], function () {
    Route::get('/', 'AdminController@index')->name('index');

    Route::resource('users', 'UserController', ['except' => ['show']] );
	Route::get('users/{user}/delete', 'UserController@destroy')->name('users.delete');

    Route::resource('pages', 'PageController', ['except' => ['show']] );
	Route::get('pages/{page}/delete', 'PageController@destroy')->name('pages.delete');

	Route::resource('cuisines', 'CuisineController', ['except' => ['show']] );
    Route::get('cuisines/{cuisine}/delete', 'CuisineController@destroy')->name('cuisines.delete');

    Route::resource('categories', 'CategoryController', ['except' => ['show']] );
	Route::get('categories/{category}/delete', 'CategoryController@destroy')->name('categories.delete');

	Route::resource('dishes', 'DishController', ['except' => ['show']] );
    Route::get('dishes/{dish}/delete', 'DishController@destroy')->name('dishes.delete');

	Route::resource('cooks', 'CookController', ['except' => ['show']] );
    Route::get('cooks/{cook}/delete', 'CookController@destroy')->name('cooks.delete');

    Route::resource('orders', 'OrderController', ['only' => ['index', 'edit', 'update']] );

	Route::resource('reviews', 'ReviewController', ['except' => ['show']] );
	Route::get('reviews/{review}/delete', 'ReviewController@destroy')->name('reviews.delete');

    Route::group(['prefix' => 'menus', 'as' => 'menus.'], function () {
        Route::get('/', 'MenuController@index')->name('index');
	    Route::post('{menu}', 'MenuController@store')->name('store');
        Route::get('{menu}', 'MenuController@show')->name('show');
        Route::get('move/{link}/{direction}', 'MenuController@move')->name('move');
        Route::get('delete/{link}', 'MenuController@delete')->name('delete');
        Route::get('edit', 'MenuController@edit')->name('edit');
        Route::post('edit', 'MenuController@update')->name('update');
    });
});


Route::get('/activate/{token}', 'Api\AuthController@activate');


//Auth::routes();


// Vue routes
Route::get('/{vue_capture?}', function() {
	return view( 'vue');
})->where('vue_capture', '[\/\w\.-]*')->name('vue');

app/Dish.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dish extends Model
{

    protected $fillable =
        [
            'cuisine_id',
            'category_id',
            'title',
            'description',
            'image',
            'price',
        ];

    public static $image_size = ['width' => 640, 'height' => 480];

    public function cuisine()
    {
        return $this->belongsTo(Cuisine::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public static function boot() {
        static::deleting(function ($model) {
            \File::delete(public_path('img/dishes/') . $model->image);
        });
    }
}

app/Http/Controllers/Api/DishController.php
<?php

namespace App\Http\Controllers\Api;

use App\Dish;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DishController extends Controller
{

	/**
	 * Get dishes Api
	 *
	 * @return \Illuminate\Http\JsonResponse
	 */
	public function index()
	{
		return response()->json(Dish::with(['cuisine', 'category'])->paginate(6));
	}

	/**
	 * Show dish Api
	 *
	 * @param $id
	 *
	 * @return \Illuminate\Http\JsonResponse
	 */
	public function show($id)
	{
		// Получаем блюдо и рекомендованные блюда
		$dish = Dish::find($id);
		$recommended = Dish::where('category_id', $dish->category->id)
		                   ->orWhere('cuisine_id', $dish->cuisine->id)
		                   ->with(['category', 'cuisine'])
		                   ->get()
		                   ->where('id', '!=', $dish->id)
		                   ->shuffle();

		return response()->json(['dish' => $dish, 'recommended' => $recommended]);
	}
}

app/Http/Controllers/DishController.php
<?php

namespace App\Http\Controllers;

use App\Cuisine;
use App\Category;
use App\Dish;
use App\Helpers;
use Illuminate\Http\Request;
use App\Http\Requests\DishRequest;

class DishController extends Controller
{

    /**
     * Вывод списка всех блюд в админке
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $dishes = Dish::all();

        return view('admin.dishes.index', compact('dishes'));
    }

    /**
     * Форма добавления нового блюда
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        // Формируем список кухонь для формы
        $cuisines = [];
        foreach (Cuisine::all() as $item) {
            $cuisines[$item->id] = $item->title;
        }

        // Формируем список категорий для формы
        $categories = [];
        foreach (Category::all() as $item) {
            $categories[$item->id] = $item->title;
        }

        $data = [
            'cuisines'   => $cuisines,
            'categories' => $categories,
        ];

        return view('admin.dishes.create', $data);
    }

    /**
     * Сохранить новое блюдо
     *
     * @param \App\Http\Requests\DishRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(DishRequest $request)
    {
        // Если передан файл, сохраняем новый файл,
        // в ответ получаем имя файла
        $image_name = Helpers::storeImage($request, new Dish);

        // Добавляем поле с именем файла
        $request->request->add(['image' => $image_name]);

        // Сохраняем запись
        Dish::create($request->all());

        return redirect()->route('admin.dishes.index')
            ->with("success", "Запись успешно создана!");
    }

    /**
     * Форма редактирования блюда
     *
     * @param \App\Dish $dish
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Dish $dish)
    {
        // Формируем список кухонь для формы
        $cuisines = [];
        foreach (Cuisine::all() as $item) {
            $cuisines[$item->id] = $item->title;
        }

        // Формируем список категорий для формы
        $categories = [];
        foreach (Category::all() as $item) {
            $categories[$item->id] = $item->title;
        }

        $data = [
            'dish'       => $dish,
            'cuisines'   => $cuisines,
            'categories' => $categories,
        ];

        return view('admin.dishes.edit', $data);
    }

    /**
     * Обновить блюдо
     *
     * @param \App\Http\Requests\DishRequest $request
     * @param \App\Dish                      $dish
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(DishRequest $request, Dish $dish)
    {
        // Если передан файл, сохраняем новый файл, удалив старый,
        // в ответ получаем имя файла
        $image_name = Helpers::replaceImage($request, $dish);

        // Добавляем поле с именем файла
        $request->request->add(['image' => $image_name]);

        // Обновляем запись
        $dish->update($request->all());

        return redirect()->back()
            ->with("success", "Запись успешно изменена!");
    }

    /**
     * Удаление блюда
     *
     * @param Request $request
     * @param Dish    $dish
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     * @throws \Exception
     */
    public function destroy(Request $request, Dish $dish)
    {
        // Если перешли методом delete, удаляем запись
        if ($request->isMethod('delete')) {
            $dish->delete();

            return redirect()->route('admin.dishes.index')
                ->with("success", "Запись удалена!");
        }

        return view('admin.dishes.delete', compact('dish'));
    }
}

resources/views/site/dishes/index.blade.php
@extends('layouts.site')

@section('pageDescription', '')
@section('pageTitle', 'Все блюда | ')

@section('content')
    <section class="dish">
        <div class="wrapper">
            <h2 class="h2">Все блюда</h2>

            @include('layouts.dishes')
        </div>
    </section>
@endsection

resources/views/site/dishes/show.blade.php
@extends('layouts.site')

@section('pageDescription', '')
@section('pageTitle', $dish->title . ' | ')

@section('content')
    <section class="dish">
        <div class="wrapper">
            {{--{{ link_to_route('dishes.index', 'Все блюда') }}--}}

            <div class="dish__show">
                <div class="image">
                    <img src="{{ asset('img/dishes/' . $dish->image) }}" alt="{{ $dish->title }}">
                </div>

                <div class="info">
                    <div class="title">{{ $dish->title }}</div>

                    <div class="links">
                        {{ link_to_route('cuisines.show', $dish->cuisine->title.' кухня', $dish->cuisine->alias) }}
                        {{ link_to_route('categories.show', $dish->category->title, $dish->category->alias) }}
                    </div>

                    <div class="description">{!! $dish->description !!}</div>
                    <div class="bottom">
                        <div class="price">Цена: {{ $dish->price }} руб.</div>
                        <a href="{{ route('cart.increase', $dish) }}" class="buy">В корзину</a>
                    </div>
                </div>
            </div>

            <div class="recommended">
                <div class="title">Похожие блюда</div>

                <div class="owl-carousel owl-theme owl-loaded owl-drag recommended__items">
                    @foreach ( $recommended as $dish )
                        <div class="item">
                            <div class="image">
                                <div class="links">
                                    {{ link_to_route('cuisines.show', $dish->cuisine->title.' кухня', $dish->cuisine->alias) }}
                                    {{ link_to_route('categories.show', $dish->category->title, $dish->category->alias) }}
                                </div>

                                <a href="{{ route('dishes.show', [$dish]) }}">
                                    <div class="overlay">
                                        <p>Посмотреть описание</p>
                                    </div>

                                    <div class="title">{{ $dish->title }}</div>

                                    <img src="{{ asset('img/dishes/' . $dish->image) }}" alt="{{ $dish->title }}">
                                </a>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </section>
@endsection